"""empty message

Revision ID: 193625f94f25
Revises: 3b78f67e2b16
Create Date: 2015-05-29 08:58:17.795804

"""

# revision identifiers, used by Alembic.
revision = '193625f94f25'
down_revision = '3b78f67e2b16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
